#!/usr/bin/env zsh

setopt INTERACTIVE_COMMENTS
setopt NOTIFY
setopt AUTO_CD
setopt AUTO_LIST
setopt AUTO_MENU
setopt AUTO_NAME_DIRS
setopt AUTO_PARAM_KEYS
setopt AUTO_PARAM_SLASH
setopt COMPLETE_ALIASES
setopt GLOB_COMPLETE
setopt EXTENDED_GLOB
setopt PROMPT_SUBST
